In [4]:
import pandas as pd

# Wczytywanie danych

In [5]:
file_path = "..\OriginalData\dem_score.xlsx"

In [23]:
final_file_path = "..\AnalysisData\dem_score_final.csv"

In [6]:
df = pd.read_excel(file_path)

In [7]:
df

            country  1952  1957  1962  1967  1972  1977  1982  1987  1992
0           Albania    -9    -9    -9    -9    -9    -9    -9    -9     5
1         Argentina    -9    -1    -1    -9    -9    -9    -8     8     7
2           Armenia    -9    -7    -7    -7    -7    -7    -7    -7     7
3         Australia    10    10    10    10    10    10    10    10    10
4           Austria    10    10    10    10    10    10    10    10    10
5        Azerbaijan    -9    -7    -7    -7    -7    -7    -7    -7     1
6           Belarus    -9    -7    -7    -7    -7    -7    -7    -7     7
7           Belgium    10    10    10    10    10    10    10    10    10
8            Bhutan   -10   -10   -10   -10   -10   -10   -10   -10   -10
9           Bolivia    -4    -3    -3    -4    -7    -7     8     9     9
10           Brazil     5     5     5    -9    -9    -4    -3     7     8
11         Bulgaria    -7    -7    -7    -7    -7    -7    -7    -7     8
12           Canada    10    10    10    10    10    10    10    10    10
13            Chile     2     5     5     6     6    -7    -7    -6     8
14            China    -8    -8    -8    -9    -8    -7    -7    -7    -7
15         Colombia    -5     7     7     7     7     8     8     8     9
16       Costa Rica    10    10    10    10    10    10    10    10    10
17          Croatia    -7    -7    -7    -7    -7    -7    -5    -5    -3
18             Cuba     0    -9    -7    -7    -7    -7    -7    -7    -7
19       Czech Rep.    -7    -7    -7    -7    -7    -7    -7    -7     8
20          Denmark    10    10    10    10    10    10    10    10    10
21   Dominican Rep.    -9    -9     8    -3    -3    -3     6     6     6
22          Ecuador     2     2    -1    -1    -5    -5     9     8     9
23            Egypt    -7    -7    -7    -7    -7    -6    -6    -6    -6
24      El Salvador    -6    -5    -3     0    -1    -6     2     6     7
25          Estonia    -9    -7    -7    -7    -7    -7    -7    -7     6
26         Ethiopia    -9    -9    -9    -9    -9    -7    -7    -8     0
27          Finland    10    10    10    10    10    10    10    10    10
28           France    10    10     5     5     8     8     8     9     9
29          Georgia    -9    -7    -7    -7    -7    -7    -7    -7     4
..              ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
66         Pakistan     5     8     1     1     4    -7    -7    -4     8
67           Panama    -1     4     4     4    -7    -7    -5    -8     8
68         Paraguay    -5    -9    -9    -8    -8    -8    -8    -8     7
69             Peru    -2     5    -6     5    -7    -7     7     7    -3
70      Philippines     5     5     5     5    -9    -9    -7     8     8
71           Poland    -7    -7    -7    -7    -7    -7    -8    -6     8
72         Portugal    -9    -9    -9    -9    -9     9    10    10    10
73          Romania    -7    -7    -7    -7    -7    -8    -8    -8     5
74           Russia    -9    -7    -7    -7    -7    -7    -7    -7     5
75     Saudi Arabia   -10   -10   -10   -10   -10   -10   -10   -10   -10
76           Serbia    -7    -7    -7    -7    -7    -7    -5    -5    -5
77  Slovak Republic    -7    -7    -7    -7    -7    -7    -7    -7     8
78         Slovenia    -7    -7    -7    -7    -7    -7    -5    -5    10
79     South Africa     4     4     4     4     4     4     4     4     6
80            Spain    -7    -7    -7    -7    -7     5    10    10    10
81        Sri Lanka     7     7     7     7     8     8     5     5     5
82           Sweden    10    10    10    10    10    10    10    10    10
83      Switzerland    10    10    10    10    10    10    10    10    10
84            Syria    -7     7    -2    -7    -9    -9    -9    -9    -9
85           Taiwan    -8    -8    -8    -8    -8    -7    -7    -1     7
86       Tajikistan    -9    -7    -7    -7    -7    -7    -7    -7    -6
87         Thailand    -6    -3    -7    -7    -7    -2     2     2     9
88           Turkey     7     4     9     8    -2     9    -5     7     9
89     Turkmenistan    -9    -7    -7    -7    -7    -7    -7    -7    -9
90          Ukraine    -9    -7    -7    -7    -7    -7    -7    -7     6
91   United Kingdom    10    10    10    10    10    10    10    10    10
92    United States    10    10    10    10    10    10    10    10    10
93          Uruguay     8     8     8     8    -3    -8    -7     9    10
94       Uzbekistan    -9    -7    -7    -7    -7    -7    -7    -7    -9
95        Venezuela    -3    -3     6     6     9     9     9     9     8

[96 rows x 10 columns]

In [17]:
data_melt = pd.melt(df,id_vars='country')

In [18]:
data_melt

             country variable  value
0            Albania     1952     -9
1          Argentina     1952     -9
2            Armenia     1952     -9
3          Australia     1952     10
4            Austria     1952     10
5         Azerbaijan     1952     -9
6            Belarus     1952     -9
7            Belgium     1952     10
8             Bhutan     1952    -10
9            Bolivia     1952     -4
10            Brazil     1952      5
11          Bulgaria     1952     -7
12            Canada     1952     10
13             Chile     1952      2
14             China     1952     -8
15          Colombia     1952     -5
16        Costa Rica     1952     10
17           Croatia     1952     -7
18              Cuba     1952      0
19        Czech Rep.     1952     -7
20           Denmark     1952     10
21    Dominican Rep.     1952     -9
22           Ecuador     1952      2
23             Egypt     1952     -7
24       El Salvador     1952     -6
25           Estonia     1952     -9
26          Ethiopia     1952     -9
27           Finland     1952     10
28            France     1952     10
29           Georgia     1952     -9
..               ...      ...    ...
834         Pakistan     1992      8
835           Panama     1992      8
836         Paraguay     1992      7
837             Peru     1992     -3
838      Philippines     1992      8
839           Poland     1992      8
840         Portugal     1992     10
841          Romania     1992      5
842           Russia     1992      5
843     Saudi Arabia     1992    -10
844           Serbia     1992     -5
845  Slovak Republic     1992      8
846         Slovenia     1992     10
847     South Africa     1992      6
848            Spain     1992     10
849        Sri Lanka     1992      5
850           Sweden     1992     10
851      Switzerland     1992     10
852            Syria     1992     -9
853           Taiwan     1992      7
854       Tajikistan     1992     -6
855         Thailand     1992      9
856           Turkey     1992      9
857     Turkmenistan     1992     -9
858          Ukraine     1992      6
859   United Kingdom     1992     10
860    United States     1992     10
861          Uruguay     1992     10
862       Uzbekistan     1992     -9
863        Venezuela     1992      8

[864 rows x 3 columns]

In [22]:
data_melt.rename(columns={"variable": "year", "value": "domocratic_lvl"}, inplace=True)

(data_melt)

             country  year  domocratic_lvl
0            Albania  1952              -9
1          Argentina  1952              -9
2            Armenia  1952              -9
3          Australia  1952              10
4            Austria  1952              10
5         Azerbaijan  1952              -9
6            Belarus  1952              -9
7            Belgium  1952              10
8             Bhutan  1952             -10
9            Bolivia  1952              -4
10            Brazil  1952               5
11          Bulgaria  1952              -7
12            Canada  1952              10
13             Chile  1952               2
14             China  1952              -8
15          Colombia  1952              -5
16        Costa Rica  1952              10
17           Croatia  1952              -7
18              Cuba  1952               0
19        Czech Rep.  1952              -7
20           Denmark  1952              10
21    Dominican Rep.  1952              -9
22           Ecuador  1952               2
23             Egypt  1952              -7
24       El Salvador  1952              -6
25           Estonia  1952              -9
26          Ethiopia  1952              -9
27           Finland  1952              10
28            France  1952              10
29           Georgia  1952              -9
..               ...   ...             ...
834         Pakistan  1992               8
835           Panama  1992               8
836         Paraguay  1992               7
837             Peru  1992              -3
838      Philippines  1992               8
839           Poland  1992               8
840         Portugal  1992              10
841          Romania  1992               5
842           Russia  1992               5
843     Saudi Arabia  1992             -10
844           Serbia  1992              -5
845  Slovak Republic  1992               8
846         Slovenia  1992              10
847     South Africa  1992               6
848            Spain  1992              10
849        Sri Lanka  1992               5
850           Sweden  1992              10
851      Switzerland  1992              10
852            Syria  1992              -9
853           Taiwan  1992               7
854       Tajikistan  1992              -6
855         Thailand  1992               9
856           Turkey  1992               9
857     Turkmenistan  1992              -9
858          Ukraine  1992               6
859   United Kingdom  1992              10
860    United States  1992              10
861          Uruguay  1992              10
862       Uzbekistan  1992              -9
863        Venezuela  1992               8

[864 rows x 3 columns]

In [29]:
data_melt.to_csv(final_file_path, index = False)

In [30]:
# Check saved data

In [31]:
saved_df = pd.read_csv(final_file_path)

In [32]:
saved_df

             country  year  domocratic_lvl
0            Albania  1952              -9
1          Argentina  1952              -9
2            Armenia  1952              -9
3          Australia  1952              10
4            Austria  1952              10
5         Azerbaijan  1952              -9
6            Belarus  1952              -9
7            Belgium  1952              10
8             Bhutan  1952             -10
9            Bolivia  1952              -4
10            Brazil  1952               5
11          Bulgaria  1952              -7
12            Canada  1952              10
13             Chile  1952               2
14             China  1952              -8
15          Colombia  1952              -5
16        Costa Rica  1952              10
17           Croatia  1952              -7
18              Cuba  1952               0
19        Czech Rep.  1952              -7
20           Denmark  1952              10
21    Dominican Rep.  1952              -9
22           Ecuador  1952               2
23             Egypt  1952              -7
24       El Salvador  1952              -6
25           Estonia  1952              -9
26          Ethiopia  1952              -9
27           Finland  1952              10
28            France  1952              10
29           Georgia  1952              -9
..               ...   ...             ...
834         Pakistan  1992               8
835           Panama  1992               8
836         Paraguay  1992               7
837             Peru  1992              -3
838      Philippines  1992               8
839           Poland  1992               8
840         Portugal  1992              10
841          Romania  1992               5
842           Russia  1992               5
843     Saudi Arabia  1992             -10
844           Serbia  1992              -5
845  Slovak Republic  1992               8
846         Slovenia  1992              10
847     South Africa  1992               6
848            Spain  1992              10
849        Sri Lanka  1992               5
850           Sweden  1992              10
851      Switzerland  1992              10
852            Syria  1992              -9
853           Taiwan  1992               7
854       Tajikistan  1992              -6
855         Thailand  1992               9
856           Turkey  1992               9
857     Turkmenistan  1992              -9
858          Ukraine  1992               6
859   United Kingdom  1992              10
860    United States  1992              10
861          Uruguay  1992              10
862       Uzbekistan  1992              -9
863        Venezuela  1992               8

[864 rows x 3 columns]